unbind c-b
set -g prefix c-a
set-option -sa terminal-features 'xterm-kitty:rgb'
set-option -g clock-mode-style 12
set -g base-index 1
setw -g pane-base-index 1
set-option -g mouse on

#plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

##keybinds
bind c-h previous-window
bind c-l next-window

# bind prefix + tab to cycle through panes
bind tab if-shell -f "#{window_zoomed_flag}" "select-pane -t :.+; resize-pane -z" "select-pane -t :.+"

bind | split-window -h
bind - split-window -v

bind s display-popup -e "\
    tmux list-sessions -f '#{session_name}' |\
    fzf --reverse --header 'jump-to-session' --preview 'tmux capture-pane -pt {}'  |\
    xargs tmux switch-client -t"

# set v to visual mode for copying, and y to yank
bind-key -t copy-mode-vi 'v' send-keys -x begin-selection
bind-key -t copy-mode-vi y send -x copy-selection-and-cancel

bind-key r source-file ~/.tmux.conf

run '/usr/share/tmux-plugin-manager/tpm'
